
version: '3.1'

services:

  mongo:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: nest-pokemon
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
